/*
 * MCuAbstraction_layer.h
 *
 *  Created on: Aug 1, 2021
 *      Author: Abdelrahman Hepish
 */

#ifndef MCUABSTRACTION_LAYER_H_
#define MCUABSTRACTION_LAYER_H_
#include <pic16f877a.h>

#define DIRECTION_REGISTER_PORTA TRISA
#define DIRECTION_REGISTER_PORTB TRISB
#define DIRECTION_REGISTER_PORTC TRISC
#define DIRECTION_REGISTER_PORTD TRISD
#define DIRECTION_REGISTER_PORTE TRISE
// #define DIRECTION_REGISTER_PORTE DDRE

#define DATA_REGISTER_READ_PORTA PORTA
#define DATA_REGISTER_READ_PORTB PORTB
#define DATA_REGISTER_READ_PORTC PORTC
#define DATA_REGISTER_READ_PORTD PORTD
#define DATA_REGISTER_READ_PORTE PORTE
// #define DATA_REGISTER_READ_PORTE PORTE

#define DATA_REGISTER_WRITE_PORTA PORTA
#define DATA_REGISTER_WRITE_PORTB PORTB
#define DATA_REGISTER_WRITE_PORTC PORTC
#define DATA_REGISTER_WRITE_PORTD PORTD
#define DATA_REGISTER_WRITE_PORTE PORTE
// #define DATA_REGISTER_WRITE_PORTE PINE

#endif /* MCUABSTRACTION_LAYER_H_ */
