/*
 * MCuAbstraction_layer.h
 *
 *  Created on: Aug 15, 2021
 *      Author: Abdelrahman Hepish
 */

#ifndef MCUABSTRACTION_LAYER_H_
#define MCUABSTRACTION_LAYER_H_
#include <avr/io.h>

#define DIRECTION_REGISTER_PORTA DDRA
#define DIRECTION_REGISTER_PORTB DDRB
#define DIRECTION_REGISTER_PORTC DDRC
#define DIRECTION_REGISTER_PORTD DDRD
// #define DIRECTION_REGISTER_PORTE DDRE

#define DATA_REGISTER_READ_PORTA PINA
#define DATA_REGISTER_READ_PORTB PINB
#define DATA_REGISTER_READ_PORTC PINC
#define DATA_REGISTER_READ_PORTD PIND
// #define DATA_REGISTER_READ_PORTE PORTE

#define DATA_REGISTER_WRITE_PORTA PORTA
#define DATA_REGISTER_WRITE_PORTB PORTB
#define DATA_REGISTER_WRITE_PORTC PORTC
#define DATA_REGISTER_WRITE_PORTD PORTD
// #define DATA_REGISTER_WRITE_PORTE PINE

#endif /* MCUABSTRACTION_LAYER_H_ */
